# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import atc_pb2 as atc__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in atc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ATCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestLanding = channel.unary_unary(
                '/atc.ATCService/RequestLanding',
                request_serializer=atc__pb2.LandingRequest.SerializeToString,
                response_deserializer=atc__pb2.ATCResponse.FromString,
                _registered_method=True)
        self.RequestTakeoff = channel.unary_unary(
                '/atc.ATCService/RequestTakeoff',
                request_serializer=atc__pb2.TakeoffRequest.SerializeToString,
                response_deserializer=atc__pb2.ATCResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/atc.ATCService/UpdateStatus',
                request_serializer=atc__pb2.StatusUpdate.SerializeToString,
                response_deserializer=atc__pb2.ATCResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/atc.ATCService/GetSystemStatus',
                request_serializer=atc__pb2.StatusRequest.SerializeToString,
                response_deserializer=atc__pb2.SystemStatus.FromString,
                _registered_method=True)


class ATCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestLanding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestTakeoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ATCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestLanding': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestLanding,
                    request_deserializer=atc__pb2.LandingRequest.FromString,
                    response_serializer=atc__pb2.ATCResponse.SerializeToString,
            ),
            'RequestTakeoff': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTakeoff,
                    request_deserializer=atc__pb2.TakeoffRequest.FromString,
                    response_serializer=atc__pb2.ATCResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=atc__pb2.StatusUpdate.FromString,
                    response_serializer=atc__pb2.ATCResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=atc__pb2.StatusRequest.FromString,
                    response_serializer=atc__pb2.SystemStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'atc.ATCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('atc.ATCService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ATCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestLanding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atc.ATCService/RequestLanding',
            atc__pb2.LandingRequest.SerializeToString,
            atc__pb2.ATCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestTakeoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atc.ATCService/RequestTakeoff',
            atc__pb2.TakeoffRequest.SerializeToString,
            atc__pb2.ATCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atc.ATCService/UpdateStatus',
            atc__pb2.StatusUpdate.SerializeToString,
            atc__pb2.ATCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/atc.ATCService/GetSystemStatus',
            atc__pb2.StatusRequest.SerializeToString,
            atc__pb2.SystemStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
